[package]
name = "log_parser"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.10"
regex = "1.5.4"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.72"
strsim = "0.10.0"
tokio = { version = "1.0", features = ["full"] }